[project]
name = 'choice-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.benefit-marketplace]
path = 'contracts/benefit-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.token-distribution]
path = 'contracts/token-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
